name: Test-hooks
on:
  repository_dispatch:
    types: [test]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        run: |
          git clone -b dev https://github.com/Skyxim/clash-core.git clash
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: |
          cd clash
          go test ./...
      - name: Build
        if: success()
        env:
          NAME: Clash.Meta
          BINDIR: bin
        run: |
          cd clash
          make -j$(($(nproc) + 1)) releases

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() && startsWith(github.ref, 'refs/tags/')}}
        with:
          tag: ${{ github.ref }}
          files: clash/bin/*
          generate_release_notes: true
