name: Release
on:
  repository_dispatch:
    types: [build]
jobs:
  BuildTest:
    runs-on: self-hosted
    steps:
      - name: Clone code
        run: |
          rm -rf ../clash
          git clone -b dev https://github.com/Skyxim/clash-core.git ../clash
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: |
          cd ../clash
          go test ./...
      - name: Build
        if: success()
        env:
          NAME: Clash.Meta
          BINDIR: bin
        run: |
          cd ../clash
          git apply ../clash-core/*.patch
          make -j$(($(nproc) + 1)) darwin-arm64 darwin-amd64 linux-amd64 linux-amd64-compatible windows-amd64 linux-arm64

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.8.0
        with:
          name: build
          allowUpdates: true
          tag: build
          commit: release
          replacesArtifacts: true
          token: ${{ secrets.TOKEN }}
          artifacts: ../clash/bin/*